security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # CHOISIR UNE SEULE METHODE CI-DESSOUS :

            ## OPTION 1 (Recommandée) - Authenticator personnalisé moderne :
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
            remember_me:
                secret: "%kernel.secret%"
                lifetime: 604800
                path: /

            ## OPTION 2 - Ancienne méthode form_login (si vous préférez) :
            # form_login:
            #     login_path: app_login
            #     check_path: app_login
            #     enable_csrf: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/client, roles: ROLE_CLIENT }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
